In [4]:
import random
import numpy as np

In [5]:
class WaterSortGame:
    def __init__(self, num_tubes,num_colors,seed):
        self.num_tubes = num_tubes
        self.num_colors = num_colors
        self.capacity = 4
        self.seed = seed
        self.initial_state = self.generate_initial_state()



    def generate_initial_state(self):
        if self.seed is not None:
            random.seed(self.seed)
            np.random.seed(self.seed)

        # Create a list whith colors in order    
        colors = np.repeat(np.arange(1, self.num_colors + 1), self.capacity)
        

        # Shuffle the list
        np.random.shuffle(colors)
        # Add the empty tubes and create the matrix
        total_slots = self.num_tubes * self.capacity
        if len(colors) < total_slots:
            zeros = np.zeros(total_slots - len(colors), dtype=int)
            colors = np.concatenate((colors, zeros))
        state = colors.reshape((self.num_tubes, self.capacity))
        return state
    

    def is_goal_state(self,state):
        is_valid = True
        i=0
        while i<self.num_tubes and is_valid:
            color = state[i,0]
            j=1
            while j<self.capacity and is_valid:
                if(state[i,j]!=color):
                    is_valid = False
                j+=1
            i+=1
        return is_valid
    

    def is_valid_state(self,t_origen, t_destino):
        is_valid = -1
        o_empty = self.is_empty(t_origen)
        d_empty = self.is_empty(t_destino)
        if o_empty: 
            return -1

        if d_empty:
            is_valid = self.capacity
        else:
             jo = self.position_first_color(t_origen)
             jd = self.position_first_color(t_destino)
             if(t_origen[jo]==t_destino[jd]):
                 is_valid = self.capacityTube(t_destino)
        return is_valid

                 
    def position_first_color(self,tube):
        j = 0
        not_found = True
        while j<self.capacity and not_found:
            if(tube[j]!=0):
                not_found = False
            j+=1
        return j-1
    
    def capacityTube(self,tube):
        return np.sum(tube == 0)

    def is_empty(self,tube):
        is_empty = True
        i = 0
        while i<self.capacity and is_empty:
            if(tube[i]!=0):
                is_empty = False
            i+=1
        return is_empty

    def state_to_tuple(self, state):
        return tuple(tuple(tube) for tube in state)
    
    def hash_state(self, state):
        return hash(self.state_to_tuple(state))


In [6]:
juego = WaterSortGame(num_tubes=5, num_colors=3, seed=42)

print("Estado inicial:")
print(juego.initial_state)

state_final = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[0,0,0,0],[0,0,0,0]])

print(juego.is_goal_state(state_final))


Estado inicial:
[[3 3 1 3]
 [2 1 1 3]
 [2 2 1 2]
 [0 0 0 0]
 [0 0 0 0]]
True
